// Dependencies:
// https://github.com/catchorg/Catch2

// Generated by CodiumAI

#include <catch2/catch_test_macros.hpp>
#include <cstdint>

TEST_CASE('Printreversedgroups()') {


    // Handles an array with more than 2 elements correctly
    SECTION('should print reversed groups when array has more than 2 elements') {
        ArrayProcessor ap;
        ap.arr = {1, 2, 3, 4, 5};
        ap.n = ap.arr.size();
        std::ostringstream output;
        std::streambuf* oldCoutBuffer = std::cout.rdbuf(output.rdbuf());
        ap.printReversedGroups();
        std::cout.rdbuf(oldCoutBuffer);
        REQUIRE(output.str() == "3 2 1 4 3 2 5 4 3 ");
    }

    // Handles an empty array without errors
    SECTION('should handle empty array without errors') {
        ArrayProcessor ap;
        ap.arr = {};
        ap.n = ap.arr.size();
        std::ostringstream output;
        std::streambuf* oldCoutBuffer = std::cout.rdbuf(output.rdbuf());
        ap.printReversedGroups();
        std::cout.rdbuf(oldCoutBuffer);
        REQUIRE(output.str().empty());
    }
}